config/routes.rb
Rails.application.routes.draw do
  resources :shortened_urls
  devise_for :users

  root to: 'shortened_urls#index'
  get ':slug', to: 'shortened_urls#redirect', as: :short_url

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shortened_url.rb
class ShortenedUrl < ApplicationRecord
  validates :full_url, format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]), message: 'is not valid.' }, presence: true
  validates :slug, presence: true, uniqueness: true

  belongs_to :user

  before_validation :generate_slug, on: :create

  private

  def generate_slug
    self.slug = SecureRandom.alphanumeric(10) if slug.blank?

    true
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shortened_urls
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shortened_urls_controller.rb
class ShortenedUrlsController < ApplicationController
  before_action :set_shortened_url, only: %i[show edit update destroy]
  before_action :check_access, only: %i[show edit update destroy]

  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: %i[redirect]

  def index
    @shortened_urls = ShortenedUrl.where(user: current_user)
  end

  def show; end

  def new
    @shortened_url = ShortenedUrl.new
  end

  def edit; end

  def create
    @shortened_url = ShortenedUrl.new(shortened_url_params)
    @shortened_url.user_id = current_user.id

    if @shortened_url.save
      redirect_to @shortened_url, notice: 'Shortened url was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @shortened_url.update(shortened_url_params)
      redirect_to @shortened_url, notice: 'Shortened url was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @shortened_url.destroy
    redirect_to shortened_urls_url, notice: 'Shortened url was successfully destroyed.'
  end

  def redirect
    full_url = AccessUrlService.call(params[:slug])

    if full_url
      redirect_to(full_url)
    else
      render 'errors/404', status: :not_found
    end
  end

  private

  def check_access
    render 'errors/403', status: :forbidden unless current_user_owner?
  end

  def current_user_owner?
    @shortened_url.user == current_user
  end

  def set_shortened_url
    @shortened_url = ShortenedUrl.find(params[:id])
  end

  def shortened_url_params
    params.require(:shortened_url).permit(:full_url, :slug, :user_id, :counter)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shortened_urls_helper.rb
module ShortenedUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shortened_urls/_form.html.erb
<%= form_with(model: shortened_url) do |form| %>
  <% if shortened_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shortened_url.errors.count, "error") %> prohibited this shortened_url from being saved:</h2>

      <ul>
        <% shortened_url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :full_url %>
    <%= form.text_field :full_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shortened_urls/edit.html.erb
<h1>Editing Shortened Url</h1>

<%= render 'form', shortened_url: @shortened_url %>

<%= link_to 'Show', @shortened_url %> |
<%= link_to 'Back', shortened_urls_path %>

app/views/shortened_urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shortened Urls</h1>

<table>
  <thead>
    <tr>
      <th>Full url</th>
      <th>Slug</th>
      <th>User</th>
      <th>Counter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shortened_urls.each do |shortened_url| %>
      <tr>
        <td><%= shortened_url.full_url %></td>
        <td><%= shortened_url.slug %></td>
        <td><%= shortened_url.user_id %></td>
        <td><%= shortened_url.counter %></td>
        <td><%= link_to 'Show', shortened_url %></td>
        <td><%= link_to 'Edit', edit_shortened_url_path(shortened_url) %></td>
        <td><%= link_to 'Destroy', shortened_url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shortened Url', new_shortened_url_path %>

app/views/shortened_urls/new.html.erb
<h1>New Shortened Url</h1>

<%= render 'form', shortened_url: @shortened_url %>

<%= link_to 'Back', shortened_urls_path %>

app/views/shortened_urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full url:</strong>
  <%= @shortened_url.full_url %>
</p>

<p>
  <strong>Shortened link:</strong>
  <%= link_to short_url_url(@shortened_url.slug), short_url_url(@shortened_url.slug) %>
</p>

<p>
  <strong>Counter:</strong>
  <%= @shortened_url.counter %>
</p>

<% if @shortened_url.user == current_user %>
<%= link_to 'Edit', edit_shortened_url_path(@shortened_url) %> |
<% end %>
<%= link_to 'Back', shortened_urls_path %>